<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TownshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('townships')->insert([
            ['region_id' => '1', 'township' => 'Gangaw',],
            ['region_id' => '1', 'township' => 'Kyaukhtu',],
            ['region_id' => '1', 'township' => 'Saw',],
            ['region_id' => '1', 'township' => 'Tilin',],
            ['region_id' => '1', 'township' => 'Chauck',],
            ['region_id' => '1', 'township' => 'Magway',],
            ['region_id' => '1', 'township' => 'Myothit',],
            ['region_id' => '1', 'township' => 'Natmauk',],
            ['region_id' => '1', 'township' => 'Taungdwingyi',],
            ['region_id' => '1', 'township' => 'Yenangyaung',],
            ['region_id' => '1', 'township' => 'Minbu',],
            ['region_id' => '1', 'township' => 'Ngape',],
            ['region_id' => '1', 'township' => 'Pwintbyu',],
            ['region_id' => '1', 'township' => 'Salin',],
            ['region_id' => '1', 'township' => 'Sidoktaya',],
            ['region_id' => '1', 'township' => 'Myaing',],
            ['region_id' => '1', 'township' => 'Pakokku',],
            ['region_id' => '1', 'township' => 'Pauk',],
            ['region_id' => '1', 'township' => 'Seikphyu',],
            ['region_id' => '1', 'township' => 'Yesagyo',],
            ['region_id' => '1', 'township' => 'Aunglan',],
            ['region_id' => '1', 'township' => 'Kamma',],
            ['region_id' => '1', 'township' => 'Mindon',],
            ['region_id' => '1', 'township' => 'Minhla',],
            ['region_id' => '1', 'township' => 'Sinbaungwe',],
            ['region_id' => '1', 'township' => 'Thayet',],
            ['region_id' => '2', 'township' => 'Kyaukse',],
            ['region_id' => '2', 'township' => 'Myittha',],
            ['region_id' => '2', 'township' => 'Sintgaing',],
            ['region_id' => '2', 'township' => 'Tada-U',],
            ['region_id' => '2', 'township' => 'Amarapura',],
            ['region_id' => '2', 'township' => 'Aungmyethazan',],
            ['region_id' => '2', 'township' => 'Chanayethazan',],
            ['region_id' => '2', 'township' => 'Chanmyathazi',],
            ['region_id' => '2', 'township' => 'Mahaaungmye',],
            ['region_id' => '2', 'township' => 'Patheingyi',],
            ['region_id' => '2', 'township' => 'Pyigyidagun',],
            ['region_id' => '2', 'township' => 'Mahlaing',],
            ['region_id' => '2', 'township' => 'Meiktila',],
            ['region_id' => '2', 'township' => 'Thazi',],
            ['region_id' => '2', 'township' => 'Wundwin',],
            ['region_id' => '2', 'township' => 'Myingyan',],
            ['region_id' => '2', 'township' => 'Natogyi',],
            ['region_id' => '2', 'township' => 'Nganzun',],
            ['region_id' => '2', 'township' => 'Thaungtha',],
            ['region_id' => '2', 'township' => 'Kyaukpadaung',],
            ['region_id' => '2', 'township' => 'Ngathayauk',],
            ['region_id' => '2', 'township' => 'Nyaung-U',],
            ['region_id' => '2', 'township' => 'Madaya',],
            ['region_id' => '2', 'township' => 'Mogok',],
            ['region_id' => '2', 'township' => 'Pyinoolwin',],
            ['region_id' => '2', 'township' => 'Singu',],
            ['region_id' => '2', 'township' => 'Tagaung',],
            ['region_id' => '2', 'township' => 'Thabeikkyin',],
            ['region_id' => '2', 'township' => 'Pyawbwe',],
            ['region_id' => '2', 'township' => 'Yamethin',],
            ['region_id' => '3', 'township' => 'Dekkhinathiri',],
            ['region_id' => '3', 'township' => 'Lewe',],
            ['region_id' => '3', 'township' => 'Pyinmana',],
            ['region_id' => '3', 'township' => 'Zabuthiri',],
            ['region_id' => '3', 'township' => 'Ottarathiri',],
            ['region_id' => '3', 'township' => 'Pobbathiri',],
            ['region_id' => '3', 'township' => 'Tatkon',],
            ['region_id' => '3', 'township' => 'Zeyarthiri',],
            ['region_id' => '4', 'township' => 'Bawlakhe',],
            ['region_id' => '4', 'township' => 'Hpasawng',],
            ['region_id' => '4', 'township' => 'Mese',],
            ['region_id' => '4', 'township' => 'Ywathit',],
            ['region_id' => '4', 'township' => 'Demoso',],
            ['region_id' => '4', 'township' => 'Hpruso',],
            ['region_id' => '4', 'township' => 'Loikaw',],
            ['region_id' => '4', 'township' => 'Shadaw',],
            ['region_id' => '5', 'township' => 'Kengtung',],
            ['region_id' => '5', 'township' => 'Mine Pauk',],
            ['region_id' => '5', 'township' => 'Minelar',],
            ['region_id' => '5', 'township' => 'Mong Khet',],
            ['region_id' => '5', 'township' => 'Mong La',],
            ['region_id' => '5', 'township' => 'Mong Yang',],
            ['region_id' => '5', 'township' => 'Mineyu',],
            ['region_id' => '5', 'township' => 'Mong Hpayak',],
            ['region_id' => '5', 'township' => 'Mong Yawng',],
            ['region_id' => '5', 'township' => 'Minekoke',],
            ['region_id' => '5', 'township' => 'Monehta',],
            ['region_id' => '5', 'township' => 'Mong Hsat',],
            ['region_id' => '5', 'township' => 'Mong Ping',],
            ['region_id' => '5', 'township' => 'Mong Tong',],
            ['region_id' => '5', 'township' => 'Ponparkyin',],
            ['region_id' => '5', 'township' => 'Tontar',],
            ['region_id' => '5', 'township' => 'Kyaing Lap',],
            ['region_id' => '5', 'township' => 'Tachileik',],
            ['region_id' => '5', 'township' => 'Talay',],
            ['region_id' => '5', 'township' => 'Kunlong',],
            ['region_id' => '5', 'township' => 'Hsipaw',],
            ['region_id' => '5', 'township' => 'Kyaukme',],
            ['region_id' => '5', 'township' => 'Mantong',],
            ['region_id' => '5', 'township' => 'Minelon',],
            ['region_id' => '5', 'township' => 'Minengaw',],
            ['region_id' => '5', 'township' => 'Namhsan',],
            ['region_id' => '5', 'township' => 'Namtu',],
            ['region_id' => '5', 'township' => 'Nawnghkio',],
            ['region_id' => '5', 'township' => 'Hsenwi',],
            ['region_id' => '5', 'township' => 'Lashio',],
            ['region_id' => '5', 'township' => 'Mongyai',],
            ['region_id' => '5', 'township' => 'Tangyan',],
            ['region_id' => '5', 'township' => 'Chinshwehaw',],
            ['region_id' => '5', 'township' => 'Konkyan',],
            ['region_id' => '5', 'township' => 'Laukkaing',],
            ['region_id' => '5', 'township' => 'Mawhtike',],
            ['region_id' => '5', 'township' => 'Kutkai',],
            ['region_id' => '5', 'township' => 'Manhero',],
            ['region_id' => '5', 'township' => 'Monekoe',],
            ['region_id' => '5', 'township' => 'Mu Se',],
            ['region_id' => '5', 'township' => 'Namhkam',],
            ['region_id' => '5', 'township' => 'Pansai',],
            ['region_id' => '5', 'township' => 'Tamoenye',],
            ['region_id' => '5', 'township' => 'Hopang',],
            ['region_id' => '5', 'township' => 'Mongmao',],
            ['region_id' => '5', 'township' => 'Namtit',],
            ['region_id' => '5', 'township' => 'Pangwaun',],
            ['region_id' => '5', 'township' => 'Panlong',],
            ['region_id' => '5', 'township' => 'Man Kan',],
            ['region_id' => '5', 'township' => 'Matman',],
            ['region_id' => '5', 'township' => 'Namphan',],
            ['region_id' => '5', 'township' => 'Pangsang Township (Pan)',],
            ['region_id' => '5', 'township' => 'Mabein',],
            ['region_id' => '5', 'township' => 'Mongmit',],
            ['region_id' => '5', 'township' => 'Homane',],
            ['region_id' => '5', 'township' => 'Kengtaung',],
            ['region_id' => '5', 'township' => 'Langkho',],
            ['region_id' => '5', 'township' => 'Mawkmai',],
            ['region_id' => '5', 'township' => 'Mong Nai',],
            ['region_id' => '5', 'township' => 'Mong Pan',],
            ['region_id' => '5', 'township' => 'Karli',],
            ['region_id' => '5', 'township' => 'Kholan',],
            ['region_id' => '5', 'township' => 'Kunhing',],
            ['region_id' => '5', 'township' => 'Kyethi',],
            ['region_id' => '5', 'township' => 'Lai-Hka',],
            ['region_id' => '5', 'township' => 'Loilen',],
            ['region_id' => '5', 'township' => 'Minenaung',],
            ['region_id' => '5', 'township' => 'Minesan',],
            ['region_id' => '5', 'township' => 'Mong Hsu',],
            ['region_id' => '5', 'township' => 'Mong Kung',],
            ['region_id' => '5', 'township' => 'Nansang',],
            ['region_id' => '5', 'township' => 'Panglong',],
            ['region_id' => '5', 'township' => 'Hopong',],
            ['region_id' => '5', 'township' => 'Hsi Hseng',],
            ['region_id' => '5', 'township' => 'Indaw',],
            ['region_id' => '5', 'township' => 'Kalaw',],
            ['region_id' => '5', 'township' => 'Kyauktalongyi',],
            ['region_id' => '5', 'township' => 'Lawksawk',],
            ['region_id' => '5', 'township' => 'Naungtayar',],
            ['region_id' => '5', 'township' => 'Nyaungshwe',],
            ['region_id' => '5', 'township' => 'Pekon',],
            ['region_id' => '5', 'township' => 'Pingdaya',],
            ['region_id' => '5', 'township' => 'Pinlaung',],
            ['region_id' => '5', 'township' => 'Taunggyi',],
            ['region_id' => '5', 'township' => 'Ywangan',],
            ['region_id' => '6', 'township' => 'Hinthada',],
            ['region_id' => '6', 'township' => 'Ingapu',],
            ['region_id' => '6', 'township' => 'Kyangin',],
            ['region_id' => '6', 'township' => 'Lemyethna',],
            ['region_id' => '6', 'township' => 'Myanaung',],
            ['region_id' => '6', 'township' => 'Zalun',],
            ['region_id' => '6', 'township' => 'Labutta',],
            ['region_id' => '6', 'township' => 'Mawlamyinegyun',],
            ['region_id' => '6', 'township' => 'Pyinsalu',],
            ['region_id' => '6', 'township' => 'Danuphyu',],
            ['region_id' => '6', 'township' => 'Ma-ubin',],
            ['region_id' => '6', 'township' => 'Nyaungdon',],
            ['region_id' => '6', 'township' => 'Pantanaw',],
            ['region_id' => '6', 'township' => 'Einme',],
            ['region_id' => '6', 'township' => 'Myaungmya',],
            ['region_id' => '6', 'township' => 'Wakema',],
            ['region_id' => '6', 'township' => 'Hainggyikyun',],
            ['region_id' => '6', 'township' => 'Kangyidaunk',],
            ['region_id' => '6', 'township' => 'Kyaunggon',],
            ['region_id' => '6', 'township' => 'Kyonpyaw',],
            ['region_id' => '6', 'township' => 'Ngapudaw',],
            ['region_id' => '6', 'township' => 'Ngathaingchaung',],
            ['region_id' => '6', 'township' => 'Ngayokaung',],
            ['region_id' => '6', 'township' => 'Ngwehsaung',],
            ['region_id' => '6', 'township' => 'Pathein',],
            ['region_id' => '6', 'township' => 'Shwethaungyan',],
            ['region_id' => '6', 'township' => 'Thabaung',],
            ['region_id' => '6', 'township' => 'Yekyi',],
            ['region_id' => '6', 'township' => 'Ahmar',],
            ['region_id' => '6', 'township' => 'Bogale',],
            ['region_id' => '6', 'township' => 'Dedaye',],
            ['region_id' => '6', 'township' => 'Kyaiklat',],
            ['region_id' => '6', 'township' => 'Pyapon',],
            ['region_id' => '7', 'township' => 'Aungmyin',],
            ['region_id' => '7', 'township' => 'Bago',],
            ['region_id' => '7', 'township' => 'Daik-U',],
            ['region_id' => '7', 'township' => 'Hpayargyi',],
            ['region_id' => '7', 'township' => 'Intagaw',],
            ['region_id' => '7', 'township' => 'Kawa',],
            ['region_id' => '7', 'township' => 'Kyauktaga',],
            ['region_id' => '7', 'township' => 'Madauk',],
            ['region_id' => '7', 'township' => 'Nyaunglebin',],
            ['region_id' => '7', 'township' => 'Peinzalot',],
            ['region_id' => '7', 'township' => 'Penwegon',],
            ['region_id' => '7', 'township' => 'Pyuntaza',],
            ['region_id' => '7', 'township' => 'Shwegyin',],
            ['region_id' => '7', 'township' => 'Thanatpin',],
            ['region_id' => '7', 'township' => 'Waw',],
            ['region_id' => '7', 'township' => 'Kanyutkwin',],
            ['region_id' => '7', 'township' => 'Kaytumadi',],
            ['region_id' => '7', 'township' => 'Kyaukkyi',],
            ['region_id' => '7', 'township' => 'Kywebwe',],
            ['region_id' => '7', 'township' => 'Mone',],
            ['region_id' => '7', 'township' => 'Myohla',],
            ['region_id' => '7', 'township' => 'Natthangwin',],
            ['region_id' => '7', 'township' => 'Nyaungbinthar',],
            ['region_id' => '7', 'township' => 'Oktwin',],
            ['region_id' => '7', 'township' => 'Pyu',],
            ['region_id' => '7', 'township' => 'Swa',],
            ['region_id' => '7', 'township' => 'Tantabin',],
            ['region_id' => '7', 'township' => 'Taungoo',],
            ['region_id' => '7', 'township' => 'Thagara',],
            ['region_id' => '7', 'township' => 'Yaeni',],
            ['region_id' => '7', 'township' => 'Yedashe',],
            ['region_id' => '7', 'township' => 'Innma',],
            ['region_id' => '7', 'township' => 'Okshipin',],
            ['region_id' => '7', 'township' => 'Padaung',],
            ['region_id' => '7', 'township' => 'Padigone',],
            ['region_id' => '7', 'township' => 'Paukkaung',],
            ['region_id' => '7', 'township' => 'Paungdale',],
            ['region_id' => '7', 'township' => 'Paungde',],
            ['region_id' => '7', 'township' => 'Pyay',],
            ['region_id' => '7', 'township' => 'Shwedaung',],
            ['region_id' => '7', 'township' => 'Sinmeswe',],
            ['region_id' => '7', 'township' => 'Thegon',],
            ['region_id' => '7', 'township' => 'Gyobingauk',],
            ['region_id' => '7', 'township' => 'Letpadan',],
            ['region_id' => '7', 'township' => 'Minhla',],
            ['region_id' => '7', 'township' => 'Monyo',],
            ['region_id' => '7', 'township' => 'Nattalin',],
            ['region_id' => '7', 'township' => 'Okpho',],
            ['region_id' => '7', 'township' => 'Ooethegone',],
            ['region_id' => '7', 'township' => 'Sitkwin',],
            ['region_id' => '7', 'township' => 'Tapun',],
            ['region_id' => '7', 'township' => 'Tharrawaddy',],
            ['region_id' => '7', 'township' => 'Thonze',],
            ['region_id' => '7', 'township' => 'Zigon',],
            ['region_id' => '8', 'township' => 'Botataung',],
            ['region_id' => '8', 'township' => 'City',],
            ['region_id' => '8', 'township' => 'Dagon Seikkan',],
            ['region_id' => '8', 'township' => 'Dawbon',],
            ['region_id' => '8', 'township' => 'East Dagon',],
            ['region_id' => '8', 'township' => 'Mingala Taungnyunt',],
            ['region_id' => '8', 'township' => 'North Dagon',],
            ['region_id' => '8', 'township' => 'North Okkalapa',],
            ['region_id' => '8', 'township' => 'Pazundaung',],
            ['region_id' => '8', 'township' => 'South Dagon',],
            ['region_id' => '8', 'township' => 'South Okkalapa',],
            ['region_id' => '8', 'township' => 'Tamwe',],
            ['region_id' => '8', 'township' => 'Thaketa',],
            ['region_id' => '8', 'township' => 'Thingangyun',],
            ['region_id' => '8', 'township' => 'Yankin',],
            ['region_id' => '8', 'township' => 'City',],
            ['region_id' => '8', 'township' => 'Hlaingthaya',],
            ['region_id' => '8', 'township' => 'Hlegu',],
            ['region_id' => '8', 'township' => 'Hmawbi',],
            ['region_id' => '8', 'township' => 'Htantabin',],
            ['region_id' => '8', 'township' => 'Insein',],
            ['region_id' => '8', 'township' => 'Mingaladon',],
            ['region_id' => '8', 'township' => 'Rural',],
            ['region_id' => '8', 'township' => 'Shwepyitha',],
            ['region_id' => '8', 'township' => 'Taikkyi',],
            ['region_id' => '8', 'township' => 'City',],
            ['region_id' => '8', 'township' => 'Cocokyun',],
            ['region_id' => '8', 'township' => 'Dala',],
            ['region_id' => '8', 'township' => 'Kawhmu',],
            ['region_id' => '8', 'township' => 'Kayan',],
            ['region_id' => '8', 'township' => 'Kungyangon',],
            ['region_id' => '8', 'township' => 'Kyauktan',],
            ['region_id' => '8', 'township' => 'Rural',],
            ['region_id' => '8', 'township' => 'Seikkyi Kanaungto',],
            ['region_id' => '8', 'township' => 'Tada',],
            ['region_id' => '8', 'township' => 'Thanlyin',],
            ['region_id' => '8', 'township' => 'Thongwa',],
            ['region_id' => '8', 'township' => 'Twante',],
            ['region_id' => '8', 'township' => 'Ahlon',],
            ['region_id' => '8', 'township' => 'Bahan',],
            ['region_id' => '8', 'township' => 'City',],
            ['region_id' => '8', 'township' => 'Dagon',],
            ['region_id' => '8', 'township' => 'Hlaing',],
            ['region_id' => '8', 'township' => 'Kamayut',],
            ['region_id' => '8', 'township' => 'Kyauktada',],
            ['region_id' => '8', 'township' => 'Kyimyindaing',],
            ['region_id' => '8', 'township' => 'Lanmadaw',],
            ['region_id' => '8', 'township' => 'Latha',],
            ['region_id' => '8', 'township' => 'Mayangon',],
            ['region_id' => '8', 'township' => 'Pabedan',],
            ['region_id' => '8', 'township' => 'Sanchaung',],
            ['region_id' => '8', 'township' => 'Seikkan',],
            ['region_id' => '9', 'township' => 'Bhamo',],
            ['region_id' => '9', 'township' => 'Dotphoneyan',],
            ['region_id' => '9', 'township' => 'Lwegel',],
            ['region_id' => '9', 'township' => 'Mansi',],
            ['region_id' => '9', 'township' => 'Momauk',],
            ['region_id' => '9', 'township' => 'Myohla',],
            ['region_id' => '9', 'township' => 'Shwegu',],
            ['region_id' => '9', 'township' => 'Hopin',],
            ['region_id' => '9', 'township' => 'Hpakant',],
            ['region_id' => '9', 'township' => 'Kamine',],
            ['region_id' => '9', 'township' => 'Mogaung',],
            ['region_id' => '9', 'township' => 'Mohnyin',],
            ['region_id' => '9', 'township' => 'Chipwi',],
            ['region_id' => '9', 'township' => 'Hsadone',],
            ['region_id' => '9', 'township' => 'Hsawlaw',],
            ['region_id' => '9', 'township' => 'Hsinbo',],
            ['region_id' => '9', 'township' => 'Injangyang',],
            ['region_id' => '9', 'township' => 'Kanpaikti',],
            ['region_id' => '9', 'township' => 'Myitkyina',],
            ['region_id' => '9', 'township' => 'Panwa',],
            ['region_id' => '9', 'township' => 'Shinbwayyan',],
            ['region_id' => '9', 'township' => 'Tanai',],
            ['region_id' => '9', 'township' => 'Waingmaw',],
            ['region_id' => '9', 'township' => 'Kawnglanghpu',],
            ['region_id' => '9', 'township' => 'Machanbaw',],
            ['region_id' => '9', 'township' => 'Nogmung',],
            ['region_id' => '9', 'township' => 'Pannandin',],
            ['region_id' => '9', 'township' => 'Putao',],
            ['region_id' => '9', 'township' => 'Sumprabum',],
            ['region_id' => '10', 'township' => 'Donhee',],
            ['region_id' => '10', 'township' => 'Hkamti',],
            ['region_id' => '10', 'township' => 'Homalin',],
            ['region_id' => '10', 'township' => 'Htanparkway',],
            ['region_id' => '10', 'township' => 'Lahe',],
            ['region_id' => '10', 'township' => 'Leshi Township (Lay)',],
            ['region_id' => '10', 'township' => 'Mobaingluk',],
            ['region_id' => '10', 'township' => 'Nanyun',],
            ['region_id' => '10', 'township' => 'Pansaung',],
            ['region_id' => '10', 'township' => 'Sonemara',],
            ['region_id' => '10', 'township' => 'Kanbalu',],
            ['region_id' => '10', 'township' => 'Kyunhla',],
            ['region_id' => '10', 'township' => 'Taze',],
            ['region_id' => '10', 'township' => 'Ye-U',],
            ['region_id' => '10', 'township' => 'Kale',],
            ['region_id' => '10', 'township' => 'Kalewa',],
            ['region_id' => '10', 'township' => 'Mingin',],
            ['region_id' => '10', 'township' => 'Banmauk',],
            ['region_id' => '10', 'township' => 'Indaw',],
            ['region_id' => '10', 'township' => 'Katha',],
            ['region_id' => '10', 'township' => 'Kawlin',],
            ['region_id' => '10', 'township' => 'Pinlebu',],
            ['region_id' => '10', 'township' => 'Tigyaing',],
            ['region_id' => '10', 'township' => 'Wuntho',],
            ['region_id' => '10', 'township' => 'Mawlaik',],
            ['region_id' => '10', 'township' => 'Paungbyin',],
            ['region_id' => '10', 'township' => 'Ayadaw',],
            ['region_id' => '10', 'township' => 'Budalin',],
            ['region_id' => '10', 'township' => 'Chaung-U',],
            ['region_id' => '10', 'township' => 'Monywa',],
            ['region_id' => '10', 'township' => 'Myaung',],
            ['region_id' => '10', 'township' => 'Myinmu',],
            ['region_id' => '10', 'township' => 'Sagaing',],
            ['region_id' => '10', 'township' => 'Khin-U',],
            ['region_id' => '10', 'township' => 'Kyaukmyaung',],
            ['region_id' => '10', 'township' => 'Shwebo',],
            ['region_id' => '10', 'township' => 'Tabayin',],
            ['region_id' => '10', 'township' => 'Wetlet',],
            ['region_id' => '10', 'township' => 'Khampat',],
            ['region_id' => '10', 'township' => 'Myothit',],
            ['region_id' => '10', 'township' => 'Tamu',],
            ['region_id' => '10', 'township' => 'Kani',],
            ['region_id' => '10', 'township' => 'Pale',],
            ['region_id' => '10', 'township' => 'Salingyi',],
            ['region_id' => '10', 'township' => 'Yinmabin',],
            ['region_id' => '11', 'township' => 'Bawgali',],
            ['region_id' => '11', 'township' => 'Hlaignbwe',],
            ['region_id' => '11', 'township' => 'Hpa-an',],
            ['region_id' => '11', 'township' => 'Leiktho',],
            ['region_id' => '11', 'township' => 'Paingkyon',],
            ['region_id' => '11', 'township' => 'Shan Ywathit',],
            ['region_id' => '11', 'township' => 'Thandaunggyi',],
            ['region_id' => '11', 'township' => 'Hpapun',],
            ['region_id' => '11', 'township' => 'Kamamaung',],
            ['region_id' => '11', 'township' => 'Kawkareik',],
            ['region_id' => '11', 'township' => 'Kyaidon',],
            ['region_id' => '11', 'township' => 'Kyain Seikgyi',],
            ['region_id' => '11', 'township' => 'Payarthonezu',],
            ['region_id' => '11', 'township' => 'Myawaddy',],
            ['region_id' => '11', 'township' => 'Sugali',],
            ['region_id' => '11', 'township' => 'Wawlaymyaing',],
            ['region_id' => '12', 'township' => 'Chaungzon',],
            ['region_id' => '12', 'township' => 'Khawzar',],
            ['region_id' => '12', 'township' => 'Kyaikkhami',],
            ['region_id' => '12', 'township' => 'Kyaikmaraw',],
            ['region_id' => '12', 'township' => 'Lamine',],
            ['region_id' => '12', 'township' => 'Mawlamyine',],
            ['region_id' => '12', 'township' => 'Mudon',],
            ['region_id' => '12', 'township' => 'Thanbyuzayat',],
            ['region_id' => '12', 'township' => 'Ye',],
            ['region_id' => '12', 'township' => 'Bilin',],
            ['region_id' => '12', 'township' => 'Kyaikto',],
            ['region_id' => '12', 'township' => 'Mottama',],
            ['region_id' => '12', 'township' => 'Paung',],
            ['region_id' => '12', 'township' => 'Suvannawadi',],
            ['region_id' => '12', 'township' => 'Thaton',],
            ['region_id' => '12', 'township' => 'Zingyeik',],
            ['region_id' => '13', 'township' => 'Dawei',],
            ['region_id' => '13', 'township' => 'Kaleinaung',],
            ['region_id' => '13', 'township' => 'Launglon',],
            ['region_id' => '13', 'township' => 'Myitta',],
            ['region_id' => '13', 'township' => 'Thayetchaung',],
            ['region_id' => '13', 'township' => 'Yebyu',],
            ['region_id' => '13', 'township' => 'Bokpyin',],
            ['region_id' => '13', 'township' => 'Karathuri',],
            ['region_id' => '13', 'township' => 'Kawthoung',],
            ['region_id' => '13', 'township' => 'Khamaukgyi',],
            ['region_id' => '13', 'township' => 'Pyigyimandaing',],
            ['region_id' => '13', 'township' => 'Kyunsu',],
            ['region_id' => '13', 'township' => 'Myeik',],
            ['region_id' => '13', 'township' => 'Palauk',],
            ['region_id' => '13', 'township' => 'Palaw',],
            ['region_id' => '13', 'township' => 'Tanintharyi',],
            ['region_id' => '14', 'township' => 'Cikha',],
            ['region_id' => '14', 'township' => 'Falam',],
            ['region_id' => '14', 'township' => 'Rikhuadal',],
            ['region_id' => '14', 'township' => 'Tiddim',],
            ['region_id' => '14', 'township' => 'Ton Zang',],
            ['region_id' => '14', 'township' => 'Hakha',],
            ['region_id' => '14', 'township' => 'Htantlang',],
            ['region_id' => '14', 'township' => 'Kanpetlet',],
            ['region_id' => '14', 'township' => 'Matupi',],
            ['region_id' => '14', 'township' => 'Mindat',],
            ['region_id' => '14', 'township' => 'Paletwa',],
            ['region_id' => '14', 'township' => 'Reazu',],
            ['region_id' => '14', 'township' => 'Sami',],
            ['region_id' => '15', 'township' => 'Ann',],
            ['region_id' => '15', 'township' => 'Kyaukpyu',],
            ['region_id' => '15', 'township' => 'Manaung',],
            ['region_id' => '15', 'township' => 'Ramree',],
            ['region_id' => '15', 'township' => 'Buthidaung',],
            ['region_id' => '15', 'township' => 'Maungdaw',],
            ['region_id' => '15', 'township' => 'Taungpyoletwe',],
            ['region_id' => '15', 'township' => 'Pauktaw',],
            ['region_id' => '15', 'township' => 'Ponnagyun',],
            ['region_id' => '15', 'township' => 'Rathedaung',],
            ['region_id' => '15', 'township' => 'Sittwe',],
            ['region_id' => '15', 'township' => 'Gaw',],
            ['region_id' => '15', 'township' => 'Kyeintali',],
            ['region_id' => '15', 'township' => 'Maei',],
            ['region_id' => '15', 'township' => 'Thandwe',],
            ['region_id' => '15', 'township' => 'Toungup',],
            ['region_id' => '15', 'township' => 'Kyauktaw',],
            ['region_id' => '15', 'township' => 'Minbya',],
            ['region_id' => '15', 'township' => 'Mrauk-U',],
            ['region_id' => '15', 'township' => 'Myebon',],
        ]);
    }
}
