<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TownshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('townships')->insert([
            ['region_id' => '1', 'township' => 'Gangaw',],
            ['region_id' => '2', 'township' => 'Kyaukhtu',],
            ['region_id' => '3', 'township' => 'Saw',],
            ['region_id' => '4', 'township' => 'Tilin',],
            ['region_id' => '5', 'township' => 'Chauck',],
            ['region_id' => '6', 'township' => 'Magway',],
            ['region_id' => '7', 'township' => 'Myothit',],
            ['region_id' => '8', 'township' => 'Natmauk',],
            ['region_id' => '9', 'township' => 'Taungdwingyi',],
            ['region_id' => '10', 'township' => 'Yenangyaung',],
            ['region_id' => '11', 'township' => 'Minbu',],
            ['region_id' => '12', 'township' => 'Ngape',],
            ['region_id' => '13', 'township' => 'Pwintbyu',],
            ['region_id' => '14', 'township' => 'Salin',],
            ['region_id' => '15', 'township' => 'Sidoktaya',],
            ['region_id' => '16', 'township' => 'Myaing',],
            ['region_id' => '17', 'township' => 'Pakokku',],
            ['region_id' => '18', 'township' => 'Pauk',],
            ['region_id' => '19', 'township' => 'Seikphyu',],
            ['region_id' => '20', 'township' => 'Yesagyo',],
            ['region_id' => '21', 'township' => 'Aunglan',],
            ['region_id' => '22', 'township' => 'Kamma',],
            ['region_id' => '23', 'township' => 'Mindon',],
            ['region_id' => '24', 'township' => 'Minhla',],
            ['region_id' => '25', 'township' => 'Sinbaungwe',],
            ['region_id' => '26', 'township' => 'Thayet',],
            ['region_id' => '27', 'township' => 'Kyaukse',],
            ['region_id' => '28', 'township' => 'Myittha',],
            ['region_id' => '29', 'township' => 'Sintgaing',],
            ['region_id' => '30', 'township' => 'Tada-U',],
            ['region_id' => '31', 'township' => 'Amarapura',],
            ['region_id' => '32', 'township' => 'Aungmyethazan',],
            ['region_id' => '33', 'township' => 'Chanayethazan',],
            ['region_id' => '34', 'township' => 'Chanmyathazi',],
            ['region_id' => '35', 'township' => 'Mahaaungmye',],
            ['region_id' => '36', 'township' => 'Patheingyi',],
            ['region_id' => '37', 'township' => 'Pyigyidagun',],
            ['region_id' => '38', 'township' => 'Mahlaing',],
            ['region_id' => '39', 'township' => 'Meiktila',],
            ['region_id' => '40', 'township' => 'Thazi',],
            ['region_id' => '41', 'township' => 'Wundwin',],
            ['region_id' => '42', 'township' => 'Myingyan',],
            ['region_id' => '43', 'township' => 'Natogyi',],
            ['region_id' => '44', 'township' => 'Nganzun',],
            ['region_id' => '45', 'township' => 'Thaungtha',],
            ['region_id' => '46', 'township' => 'Kyaukpadaung',],
            ['region_id' => '47', 'township' => 'Ngathayauk',],
            ['region_id' => '48', 'township' => 'Nyaung-U',],
            ['region_id' => '49', 'township' => 'Madaya',],
            ['region_id' => '50', 'township' => 'Mogok',],
            ['region_id' => '51', 'township' => 'Pyinoolwin',],
            ['region_id' => '52', 'township' => 'Singu',],
            ['region_id' => '53', 'township' => 'Tagaung',],
            ['region_id' => '54', 'township' => 'Thabeikkyin',],
            ['region_id' => '55', 'township' => 'Pyawbwe',],
            ['region_id' => '56', 'township' => 'Yamethin',],
            ['region_id' => '57', 'township' => 'Dekkhinathiri',],
            ['region_id' => '58', 'township' => 'Lewe',],
            ['region_id' => '59', 'township' => 'Pyinmana',],
            ['region_id' => '60', 'township' => 'Zabuthiri',],
            ['region_id' => '61', 'township' => 'Ottarathiri',],
            ['region_id' => '62', 'township' => 'Pobbathiri',],
            ['region_id' => '63', 'township' => 'Tatkon',],
            ['region_id' => '64', 'township' => 'Zeyarthiri',],
            ['region_id' => '65', 'township' => 'Bawlakhe',],
            ['region_id' => '66', 'township' => 'Hpasawng',],
            ['region_id' => '67', 'township' => 'Mese',],
            ['region_id' => '68', 'township' => 'Ywathit',],
            ['region_id' => '69', 'township' => 'Demoso',],
            ['region_id' => '70', 'township' => 'Hpruso',],
            ['region_id' => '71', 'township' => 'Loikaw',],
            ['region_id' => '72', 'township' => 'Shadaw',],
            ['region_id' => '73', 'township' => 'Kengtung',],
            ['region_id' => '74', 'township' => 'Mine Pauk',],
            ['region_id' => '75', 'township' => 'Minelar',],
            ['region_id' => '76', 'township' => 'Mong Khet',],
            ['region_id' => '77', 'township' => 'Mong La',],
            ['region_id' => '78', 'township' => 'Mong Yang',],
            ['region_id' => '79', 'township' => 'Mineyu',],
            ['region_id' => '80', 'township' => 'Mong Hpayak',],
            ['region_id' => '81', 'township' => 'Mong Yawng',],
            ['region_id' => '82', 'township' => 'Minekoke',],
            ['region_id' => '83', 'township' => 'Monehta',],
            ['region_id' => '84', 'township' => 'Mong Hsat',],
            ['region_id' => '85', 'township' => 'Mong Ping',],
            ['region_id' => '86', 'township' => 'Mong Tong',],
            ['region_id' => '87', 'township' => 'Ponparkyin',],
            ['region_id' => '88', 'township' => 'Tontar',],
            ['region_id' => '89', 'township' => 'Kyaing Lap',],
            ['region_id' => '90', 'township' => 'Tachileik',],
            ['region_id' => '91', 'township' => 'Talay',],
            ['region_id' => '92', 'township' => 'Kunlong',],
            ['region_id' => '93', 'township' => 'Hsipaw',],
            ['region_id' => '94', 'township' => 'Kyaukme',],
            ['region_id' => '95', 'township' => 'Mantong',],
            ['region_id' => '96', 'township' => 'Minelon',],
            ['region_id' => '97', 'township' => 'Minengaw',],
            ['region_id' => '98', 'township' => 'Namhsan',],
            ['region_id' => '99', 'township' => 'Namtu',],
            ['region_id' => '100', 'township' => 'Nawnghkio',],
            ['region_id' => '101', 'township' => 'Hsenwi',],
            ['region_id' => '102', 'township' => 'Lashio',],
            ['region_id' => '103', 'township' => 'Mongyai',],
            ['region_id' => '104', 'township' => 'Tangyan',],
            ['region_id' => '105', 'township' => 'Chinshwehaw',],
            ['region_id' => '106', 'township' => 'Konkyan',],
            ['region_id' => '107', 'township' => 'Laukkaing',],
            ['region_id' => '108', 'township' => 'Mawhtike',],
            ['region_id' => '109', 'township' => 'Kutkai',],
            ['region_id' => '110', 'township' => 'Manhero',],
            ['region_id' => '111', 'township' => 'Monekoe',],
            ['region_id' => '112', 'township' => 'Mu Se',],
            ['region_id' => '113', 'township' => 'Namhkam',],
            ['region_id' => '114', 'township' => 'Pansai',],
            ['region_id' => '115', 'township' => 'Tamoenye',],
            ['region_id' => '116', 'township' => 'Hopang',],
            ['region_id' => '117', 'township' => 'Mongmao',],
            ['region_id' => '118', 'township' => 'Namtit',],
            ['region_id' => '119', 'township' => 'Pangwaun',],
            ['region_id' => '120', 'township' => 'Panlong',],
            ['region_id' => '121', 'township' => 'Man Kan',],
            ['region_id' => '122', 'township' => 'Matman',],
            ['region_id' => '123', 'township' => 'Namphan',],
            ['region_id' => '124', 'township' => 'Pangsang Township (Pan',],
            ['region_id' => '125', 'township' => 'Mabein',],
            ['region_id' => '126', 'township' => 'Mongmit',],
            ['region_id' => '127', 'township' => 'Homane',],
            ['region_id' => '128', 'township' => 'Kengtaung',],
            ['region_id' => '129', 'township' => 'Langkho',],
            ['region_id' => '130', 'township' => 'Mawkmai',],
            ['region_id' => '131', 'township' => 'Mong Nai',],
            ['region_id' => '132', 'township' => 'Mong Pan',],
            ['region_id' => '133', 'township' => 'Karli',],
            ['region_id' => '134', 'township' => 'Kholan',],
            ['region_id' => '135', 'township' => 'Kunhing',],
            ['region_id' => '136', 'township' => 'Kyethi',],
            ['region_id' => '137', 'township' => 'Lai-Hka',],
            ['region_id' => '138', 'township' => 'Loilen',],
            ['region_id' => '139', 'township' => 'Minenaung',],
            ['region_id' => '140', 'township' => 'Minesan',],
            ['region_id' => '141', 'township' => 'Mong Hsu',],
            ['region_id' => '142', 'township' => 'Mong Kung',],
            ['region_id' => '143', 'township' => 'Nansang',],
            ['region_id' => '144', 'township' => 'Panglong',],
            ['region_id' => '145', 'township' => 'Hopong',],
            ['region_id' => '146', 'township' => 'Hsi Hseng',],
            ['region_id' => '147', 'township' => 'Indaw',],
            ['region_id' => '148', 'township' => 'Kalaw',],
            ['region_id' => '149', 'township' => 'Kyauktalongyi',],
            ['region_id' => '150', 'township' => 'Lawksawk',],
            ['region_id' => '151', 'township' => 'Naungtayar',],
            ['region_id' => '152', 'township' => 'Nyaungshwe',],
            ['region_id' => '153', 'township' => 'Pekon',],
            ['region_id' => '154', 'township' => 'Pingdaya',],
            ['region_id' => '155', 'township' => 'Pinlaung',],
            ['region_id' => '156', 'township' => 'Taunggyi',],
            ['region_id' => '157', 'township' => 'Ywangan',],
            ['region_id' => '158', 'township' => 'Hinthada',],
            ['region_id' => '159', 'township' => 'Ingapu',],
            ['region_id' => '160', 'township' => 'Kyangin',],
            ['region_id' => '161', 'township' => 'Lemyethna',],
            ['region_id' => '162', 'township' => 'Myanaung',],
            ['region_id' => '163', 'township' => 'Zalun',],
            ['region_id' => '164', 'township' => 'Labutta',],
            ['region_id' => '165', 'township' => 'Mawlamyinegyun',],
            ['region_id' => '166', 'township' => 'Pyinsalu',],
            ['region_id' => '167', 'township' => 'Danuphyu',],
            ['region_id' => '168', 'township' => 'Ma-ubin',],
            ['region_id' => '169', 'township' => 'Nyaungdon',],
            ['region_id' => '170', 'township' => 'Pantanaw',],
            ['region_id' => '171', 'township' => 'Einme',],
            ['region_id' => '172', 'township' => 'Myaungmya',],
            ['region_id' => '173', 'township' => 'Wakema',],
            ['region_id' => '174', 'township' => 'Hainggyikyun',],
            ['region_id' => '175', 'township' => 'Kangyidaunk',],
            ['region_id' => '176', 'township' => 'Kyaunggon',],
            ['region_id' => '177', 'township' => 'Kyonpyaw',],
            ['region_id' => '178', 'township' => 'Ngapudaw',],
            ['region_id' => '179', 'township' => 'Ngathaingchaung',],
            ['region_id' => '180', 'township' => 'Ngayokaung',],
            ['region_id' => '181', 'township' => 'Ngwehsaung',],
            ['region_id' => '182', 'township' => 'Pathein',],
            ['region_id' => '183', 'township' => 'Shwethaungyan',],
            ['region_id' => '184', 'township' => 'Thabaung',],
            ['region_id' => '185', 'township' => 'Yekyi',],
            ['region_id' => '186', 'township' => 'Ahmar',],
            ['region_id' => '187', 'township' => 'Bogale',],
            ['region_id' => '188', 'township' => 'Dedaye',],
            ['region_id' => '189', 'township' => 'Kyaiklat',],
            ['region_id' => '190', 'township' => 'Pyapon',],
            ['region_id' => '191', 'township' => 'Aungmyin',],
            ['region_id' => '192', 'township' => 'Bago',],
            ['region_id' => '193', 'township' => 'Daik-U',],
            ['region_id' => '194', 'township' => 'Hpayargyi',],
            ['region_id' => '195', 'township' => 'Intagaw',],
            ['region_id' => '196', 'township' => 'Kawa',],
            ['region_id' => '197', 'township' => 'Kyauktaga',],
            ['region_id' => '198', 'township' => 'Madauk',],
            ['region_id' => '199', 'township' => 'Nyaunglebin',],
            ['region_id' => '200', 'township' => 'Peinzalot',],
            ['region_id' => '201', 'township' => 'Penwegon',],
            ['region_id' => '202', 'township' => 'Pyuntaza',],
            ['region_id' => '203', 'township' => 'Shwegyin',],
            ['region_id' => '204', 'township' => 'Thanatpin',],
            ['region_id' => '205', 'township' => 'Waw',],
            ['region_id' => '206', 'township' => 'Kanyutkwin',],
            ['region_id' => '207', 'township' => 'Kaytumadi',],
            ['region_id' => '208', 'township' => 'Kyaukkyi',],
            ['region_id' => '209', 'township' => 'Kywebwe',],
            ['region_id' => '210', 'township' => 'Mone',],
            ['region_id' => '211', 'township' => 'Myohla',],
            ['region_id' => '212', 'township' => 'Natthangwin',],
            ['region_id' => '213', 'township' => 'Nyaungbinthar',],
            ['region_id' => '214', 'township' => 'Oktwin',],
            ['region_id' => '215', 'township' => 'Pyu',],
            ['region_id' => '216', 'township' => 'Swa',],
            ['region_id' => '217', 'township' => 'Tantabin',],
            ['region_id' => '218', 'township' => 'Taungoo',],
            ['region_id' => '219', 'township' => 'Thagara',],
            ['region_id' => '220', 'township' => 'Yaeni',],
            ['region_id' => '221', 'township' => 'Yedashe',],
            ['region_id' => '222', 'township' => 'Innma',],
            ['region_id' => '223', 'township' => 'Okshipin',],
            ['region_id' => '224', 'township' => 'Padaung',],
            ['region_id' => '225', 'township' => 'Padigone',],
            ['region_id' => '226', 'township' => 'Paukkaung',],
            ['region_id' => '227', 'township' => 'Paungdale',],
            ['region_id' => '228', 'township' => 'Paungde',],
            ['region_id' => '229', 'township' => 'Pyay',],
            ['region_id' => '230', 'township' => 'Shwedaung',],
            ['region_id' => '231', 'township' => 'Sinmeswe',],
            ['region_id' => '232', 'township' => 'Thegon',],
            ['region_id' => '233', 'township' => 'Gyobingauk',],
            ['region_id' => '234', 'township' => 'Letpadan',],
            ['region_id' => '235', 'township' => 'Minhla',],
            ['region_id' => '236', 'township' => 'Monyo',],
            ['region_id' => '237', 'township' => 'Nattalin',],
            ['region_id' => '238', 'township' => 'Okpho',],
            ['region_id' => '239', 'township' => 'Ooethegone',],
            ['region_id' => '240', 'township' => 'Sitkwin',],
            ['region_id' => '241', 'township' => 'Tapun',],
            ['region_id' => '242', 'township' => 'Tharrawaddy',],
            ['region_id' => '243', 'township' => 'Thonze',],
            ['region_id' => '244', 'township' => 'Zigon',],
            ['region_id' => '245', 'township' => 'Botataung',],
            ['region_id' => '246', 'township' => 'City',],
            ['region_id' => '247', 'township' => 'Dagon Seikkan',],
            ['region_id' => '248', 'township' => 'Dawbon',],
            ['region_id' => '249', 'township' => 'East Dagon',],
            ['region_id' => '250', 'township' => 'Mingala Taungnyunt',],
            ['region_id' => '251', 'township' => 'North Dagon',],
            ['region_id' => '252', 'township' => 'North Okkalapa',],
            ['region_id' => '253', 'township' => 'Pazundaung',],
            ['region_id' => '254', 'township' => 'South Dagon',],
            ['region_id' => '255', 'township' => 'South Okkalapa',],
            ['region_id' => '256', 'township' => 'Tamwe',],
            ['region_id' => '257', 'township' => 'Thaketa',],
            ['region_id' => '258', 'township' => 'Thingangyun',],
            ['region_id' => '259', 'township' => 'Yankin',],
            ['region_id' => '260', 'township' => 'City',],
            ['region_id' => '261', 'township' => 'Hlaingthaya',],
            ['region_id' => '262', 'township' => 'Hlegu',],
            ['region_id' => '263', 'township' => 'Hmawbi',],
            ['region_id' => '264', 'township' => 'Htantabin',],
            ['region_id' => '265', 'township' => 'Insein',],
            ['region_id' => '266', 'township' => 'Mingaladon',],
            ['region_id' => '267', 'township' => 'Rural',],
            ['region_id' => '268', 'township' => 'Shwepyitha',],
            ['region_id' => '269', 'township' => 'Taikkyi',],
            ['region_id' => '270', 'township' => 'City',],
            ['region_id' => '271', 'township' => 'Cocokyun',],
            ['region_id' => '272', 'township' => 'Dala',],
            ['region_id' => '273', 'township' => 'Kawhmu',],
            ['region_id' => '274', 'township' => 'Kayan',],
            ['region_id' => '275', 'township' => 'Kungyangon',],
            ['region_id' => '276', 'township' => 'Kyauktan',],
            ['region_id' => '277', 'township' => 'Rural',],
            ['region_id' => '278', 'township' => 'Seikkyi Kanaungto',],
            ['region_id' => '279', 'township' => 'Tada',],
            ['region_id' => '280', 'township' => 'Thanlyin',],
            ['region_id' => '281', 'township' => 'Thongwa',],
            ['region_id' => '282', 'township' => 'Twante',],
            ['region_id' => '283', 'township' => 'Ahlon',],
            ['region_id' => '284', 'township' => 'Bahan',],
            ['region_id' => '285', 'township' => 'City',],
            ['region_id' => '286', 'township' => 'Dagon',],
            ['region_id' => '287', 'township' => 'Hlaing',],
            ['region_id' => '288', 'township' => 'Kamayut',],
            ['region_id' => '289', 'township' => 'Kyauktada',],
            ['region_id' => '290', 'township' => 'Kyimyindaing',],
            ['region_id' => '291', 'township' => 'Lanmadaw',],
            ['region_id' => '292', 'township' => 'Latha',],
            ['region_id' => '293', 'township' => 'Mayangon',],
            ['region_id' => '294', 'township' => 'Pabedan',],
            ['region_id' => '295', 'township' => 'Sanchaung',],
            ['region_id' => '296', 'township' => 'Seikkan',],
            ['region_id' => '297', 'township' => 'Bhamo',],
            ['region_id' => '298', 'township' => 'Dotphoneyan',],
            ['region_id' => '299', 'township' => 'Lwegel',],
            ['region_id' => '300', 'township' => 'Mansi',],
            ['region_id' => '301', 'township' => 'Momauk',],
            ['region_id' => '302', 'township' => 'Myohla',],
            ['region_id' => '303', 'township' => 'Shwegu',],
            ['region_id' => '304', 'township' => 'Hopin',],
            ['region_id' => '305', 'township' => 'Hpakant',],
            ['region_id' => '306', 'township' => 'Kamine',],
            ['region_id' => '307', 'township' => 'Mogaung',],
            ['region_id' => '308', 'township' => 'Mohnyin',],
            ['region_id' => '309', 'township' => 'Chipwi',],
            ['region_id' => '310', 'township' => 'Hsadone',],
            ['region_id' => '311', 'township' => 'Hsawlaw',],
            ['region_id' => '312', 'township' => 'Hsinbo',],
            ['region_id' => '313', 'township' => 'Injangyang',],
            ['region_id' => '314', 'township' => 'Kanpaikti',],
            ['region_id' => '315', 'township' => 'Myitkyina',],
            ['region_id' => '316', 'township' => 'Panwa',],
            ['region_id' => '317', 'township' => 'Shinbwayyan',],
            ['region_id' => '318', 'township' => 'Tanai',],
            ['region_id' => '319', 'township' => 'Waingmaw',],
            ['region_id' => '320', 'township' => 'Kawnglanghpu',],
            ['region_id' => '321', 'township' => 'Machanbaw',],
            ['region_id' => '322', 'township' => 'Nogmung',],
            ['region_id' => '323', 'township' => 'Pannandin',],
            ['region_id' => '324', 'township' => 'Putao',],
            ['region_id' => '325', 'township' => 'Sumprabum',],
            ['region_id' => '326', 'township' => 'Donhee',],
            ['region_id' => '327', 'township' => 'Hkamti',],
            ['region_id' => '328', 'township' => 'Homalin',],
            ['region_id' => '329', 'township' => 'Htanparkway',],
            ['region_id' => '330', 'township' => 'Lahe',],
            ['region_id' => '331', 'township' => 'Leshi Township (Lay',],
            ['region_id' => '332', 'township' => 'Mobaingluk',],
            ['region_id' => '333', 'township' => 'Nanyun',],
            ['region_id' => '334', 'township' => 'Pansaung',],
            ['region_id' => '335', 'township' => 'Sonemara',],
            ['region_id' => '336', 'township' => 'Kanbalu',],
            ['region_id' => '337', 'township' => 'Kyunhla',],
            ['region_id' => '338', 'township' => 'Taze',],
            ['region_id' => '339', 'township' => 'Ye-U',],
            ['region_id' => '340', 'township' => 'Kale',],
            ['region_id' => '341', 'township' => 'Kalewa',],
            ['region_id' => '342', 'township' => 'Mingin',],
            ['region_id' => '343', 'township' => 'Banmauk',],
            ['region_id' => '344', 'township' => 'Indaw',],
            ['region_id' => '345', 'township' => 'Katha',],
            ['region_id' => '346', 'township' => 'Kawlin',],
            ['region_id' => '347', 'township' => 'Pinlebu',],
            ['region_id' => '348', 'township' => 'Tigyaing',],
            ['region_id' => '349', 'township' => 'Wuntho',],
            ['region_id' => '350', 'township' => 'Mawlaik',],
            ['region_id' => '351', 'township' => 'Paungbyin',],
            ['region_id' => '352', 'township' => 'Ayadaw',],
            ['region_id' => '353', 'township' => 'Budalin',],
            ['region_id' => '354', 'township' => 'Chaung-U',],
            ['region_id' => '355', 'township' => 'Monywa',],
            ['region_id' => '356', 'township' => 'Myaung',],
            ['region_id' => '357', 'township' => 'Myinmu',],
            ['region_id' => '358', 'township' => 'Sagaing',],
            ['region_id' => '359', 'township' => 'Khin-U',],
            ['region_id' => '360', 'township' => 'Kyaukmyaung',],
            ['region_id' => '361', 'township' => 'Shwebo',],
            ['region_id' => '362', 'township' => 'Tabayin',],
            ['region_id' => '363', 'township' => 'Wetlet',],
            ['region_id' => '364', 'township' => 'Khampat',],
            ['region_id' => '365', 'township' => 'Myothit',],
            ['region_id' => '366', 'township' => 'Tamu',],
            ['region_id' => '367', 'township' => 'Kani',],
            ['region_id' => '368', 'township' => 'Pale',],
            ['region_id' => '369', 'township' => 'Salingyi',],
            ['region_id' => '370', 'township' => 'Yinmabin',],
            ['region_id' => '371', 'township' => 'Bawgali',],
            ['region_id' => '372', 'township' => 'Hlaignbwe',],
            ['region_id' => '373', 'township' => 'Hpa-an',],
            ['region_id' => '374', 'township' => 'Leiktho',],
            ['region_id' => '375', 'township' => 'Paingkyon',],
            ['region_id' => '376', 'township' => 'Shan Ywathit',],
            ['region_id' => '377', 'township' => 'Thandaunggyi',],
            ['region_id' => '378', 'township' => 'Hpapun',],
            ['region_id' => '379', 'township' => 'Kamamaung',],
            ['region_id' => '380', 'township' => 'Kawkareik',],
            ['region_id' => '381', 'township' => 'Kyaidon',],
            ['region_id' => '382', 'township' => 'Kyain Seikgyi',],
            ['region_id' => '383', 'township' => 'Payarthonezu',],
            ['region_id' => '384', 'township' => 'Myawaddy',],
            ['region_id' => '385', 'township' => 'Sugali',],
            ['region_id' => '386', 'township' => 'Wawlaymyaing',],
            ['region_id' => '387', 'township' => 'Chaungzon',],
            ['region_id' => '388', 'township' => 'Khawzar',],
            ['region_id' => '389', 'township' => 'Kyaikkhami',],
            ['region_id' => '390', 'township' => 'Kyaikmaraw',],
            ['region_id' => '391', 'township' => 'Lamine',],
            ['region_id' => '392', 'township' => 'Mawlamyine',],
            ['region_id' => '393', 'township' => 'Mudon',],
            ['region_id' => '394', 'township' => 'Thanbyuzayat',],
            ['region_id' => '395', 'township' => 'Ye',],
            ['region_id' => '396', 'township' => 'Bilin',],
            ['region_id' => '397', 'township' => 'Kyaikto',],
            ['region_id' => '398', 'township' => 'Mottama',],
            ['region_id' => '399', 'township' => 'Paung',],
            ['region_id' => '400', 'township' => 'Suvannawadi',],
            ['region_id' => '401', 'township' => 'Thaton',],
            ['region_id' => '402', 'township' => 'Zingyeik',],
            ['region_id' => '403', 'township' => 'Dawei',],
            ['region_id' => '404', 'township' => 'Kaleinaung',],
            ['region_id' => '405', 'township' => 'Launglon',],
            ['region_id' => '406', 'township' => 'Myitta',],
            ['region_id' => '407', 'township' => 'Thayetchaung',],
            ['region_id' => '408', 'township' => 'Yebyu',],
            ['region_id' => '409', 'township' => 'Bokpyin',],
            ['region_id' => '410', 'township' => 'Karathuri',],
            ['region_id' => '411', 'township' => 'Kawthoung',],
            ['region_id' => '412', 'township' => 'Khamaukgyi',],
            ['region_id' => '413', 'township' => 'Pyigyimandaing',],
            ['region_id' => '414', 'township' => 'Kyunsu',],
            ['region_id' => '415', 'township' => 'Myeik',],
            ['region_id' => '416', 'township' => 'Palauk',],
            ['region_id' => '417', 'township' => 'Palaw',],
            ['region_id' => '418', 'township' => 'Tanintharyi',],
            ['region_id' => '419', 'township' => 'Cikha',],
            ['region_id' => '420', 'township' => 'Falam',],
            ['region_id' => '421', 'township' => 'Rikhuadal',],
            ['region_id' => '422', 'township' => 'Tiddim',],
            ['region_id' => '423', 'township' => 'Ton Zang',],
            ['region_id' => '424', 'township' => 'Hakha',],
            ['region_id' => '425', 'township' => 'Htantlang',],
            ['region_id' => '426', 'township' => 'Kanpetlet',],
            ['region_id' => '427', 'township' => 'Matupi',],
            ['region_id' => '428', 'township' => 'Mindat',],
            ['region_id' => '429', 'township' => 'Paletwa',],
            ['region_id' => '430', 'township' => 'Reazu',],
            ['region_id' => '431', 'township' => 'Sami',],
            ['region_id' => '432', 'township' => 'Ann',],
            ['region_id' => '433', 'township' => 'Kyaukpyu',],
            ['region_id' => '434', 'township' => 'Manaung',],
            ['region_id' => '435', 'township' => 'Ramree',],
            ['region_id' => '436', 'township' => 'Buthidaung',],
            ['region_id' => '437', 'township' => 'Maungdaw',],
            ['region_id' => '438', 'township' => 'Taungpyoletwe',],
            ['region_id' => '439', 'township' => 'Pauktaw',],
            ['region_id' => '440', 'township' => 'Ponnagyun',],
            ['region_id' => '441', 'township' => 'Rathedaung',],
            ['region_id' => '442', 'township' => 'Sittwe',],
            ['region_id' => '443', 'township' => 'Gaw',],
            ['region_id' => '444', 'township' => 'Kyeintali',],
            ['region_id' => '445', 'township' => 'Maei',],
            ['region_id' => '446', 'township' => 'Thandwe',],
            ['region_id' => '447', 'township' => 'Toungup',],
            ['region_id' => '448', 'township' => 'Kyauktaw',],
            ['region_id' => '449', 'township' => 'Minbya',],
            ['region_id' => '450', 'township' => 'Mrauk-U',],
            ['region_id' => '451', 'township' => 'Myebon',],
        ]);
    }
}
